### ISSUE TITLE
[Bug] Return YouTube Dislikes no longer working on New Interface

### ISSUE THREAD

**Issue by arichorn** [PoomSmart/Return-YouTube-Dislikes#16] opened 2022-08-13 20:41 UTC
![525C2FC4-193D-4288-8987-FFF84D93B2BB](https://user-images.githubusercontent.com/78001398/184509998-150d4a96-479c-40c8-9d27-3959433da37d.jpeg)
After 6 months, YouTube finally rolled out the worst UI in the video player. and unfortunately they removed the dislike text/counter & subscribe button.
It’s unfortunate to let you know about this but I do hope the Fake YouTube Version on YouPiP still works as long as YouTube doesn’t mess and change something in the code if it is server-side.
and I do hate how YouTube is trying to stop all of us from using the Return YouTube Dislikes Tweak/Extension.

Here’s this for other peoples information about this. #11 #15

**Comment by arichorn** [comment] 2022-08-16 21:54
YouTube reverted it back to the previous design for me but they changed the dislike api so I pretty sure that needs to be changed since it now shows FAILED on the dislike texts immediately after playing a video. but YouPiP’s fake version does fix it.

 I hate when YouTube does Server-Side since it effects a lot of amazing tweaks.

**Comment by PoomSmart** [comment] 2022-08-17 15:37
Does that happen to every video? I can't reproduce it.

**Comment by arichorn** [comment] 2022-08-18 00:04
It’s alright, there’s a reason why we have the option to toggle the YouTube Fake Version setting to fix that, hopefully this stay working until YouTube messes with that too. 😭

**Comment by alexandrius** [comment] 2022-08-19 04:06
@PoomSmart I believe it was enabled for limit time/users. It’s back to original now

**Comment by arichorn** [comment] 2022-08-20 04:43
I hope it stays like that tho, I don’t want YouTube to ruin this tweak

**Comment by PoomSmart** [comment] 2022-09-10 11:56
![image](https://user-images.githubusercontent.com/3608783/189482154-32961e0b-3b65-4351-bd11-39f4670a9f19.png)

This is the best I can achieve at the moment, please file a new issue if you prefer the conventional way.

Will be part of 1.6.8 release.

**Closed by PoomSmart** 2022-09-10 11:56 UTC

**Comment by arichorn** [comment] 2022-09-10 21:34
This isn’t bad! It works out and it is a cool alternative way to make the tweak work on the new ui!
